### ISSUE TITLE
doesnt these ffiles go under the gearswap folder and then job files into the gearswap>datafolder?  it dont seam to work right  gives me errors about cant find include ><

### ISSUE THREAD

**Issue by zaxtiss** [smd111/Gearswap#1]

**Comment by smd111** [comment]
i have the correct data in SMDinclude/includes/info/Basic Info.txt

but i just added it to the readme

to use these includes place them in gearswap/common/
and put your main files in eather gearswap/data/ or  gearswap/data/<playername>/
