### ISSUE TITLE
Macros with st,stnpc,stpc

### ISSUE THREAD

**Issue by Kilgannon2113** [smd111/Gearswap#2]
Any job ability or spell macro with a st\* in it will be canceled with no select target marker.

GearSwap (Debug Mode): Action canceled (/ma "Cure IV" <st>)

**Comment by smd111** [comment]
you do know that all st\* does is bring up the selection arrows and its only useful from macros

however i can add an exception for this its not that hard to do
give me some time (a week or so) and this will be fixed

**Comment by Kilgannon2113** [comment]
Yea. I managed to get a target selector by adding rules to pretarget, but don't know enough to get the game to wait for input before casting spells (casts on primary target then brings up select target)

**Comment by smd111** [comment]
if you use the menu it will always bring up the target selection arrow

**Comment by smd111** [comment]
pushed let me know if it works

**Comment by Kilgannon2113** [comment]
Works great. Thank you.
