### ISSUE TITLE
No abilities or spells can be cast in town 

### ISSUE THREAD

**Issue by Kilgannon2113** [smd111/Gearswap#3]
Tested in Mhaura and Bastok Mines

Abilities and Spells cast while in towns either by macro or menu are not used. 

No Debug Mode info via menu

info via Macro
GearSwap (Debug Mode): Action canceled (/ja "Protectra V" <me>)

**Comment by smd111** [comment]
yes that's built in to this

the only spells that you should ever need to use in a town are teleport spells

```
    --Stops all spells but teleport spells in cities
    elseif not transportation_spells:contains(spell.en) and cities:contains(world.area) then
        return true
```

**Comment by Kilgannon2113** [comment]
Except for pre buffs Pro and shell for ambuscade which is how I found it. Maybe the occasional flee if you were on thf, though I think I've only seen used in town once since I've returned.

I'll edit for my purposes.

Thank you for the updates. Really like the layout, and on screen menu.

**Comment by smd111** [comment]
i could add a switch to enable or disable that if you would like??

**Comment by smd111** [comment]
pushed let me know if it works

**Comment by Kilgannon2113** [comment]
Works great. Thank you.
