### ISSUE TITLE
Pup.lua, Basic.lua & Basic info.txt

### ISSUE THREAD

**Issue by Kilgannon2113** [smd111/Gearswap#4]
PUP.lua

Line 121: Remove function (again)

Enabling auto pup:
Gives following error
GearSwap: Lua runtime error: GearSwap/data/PUP.lua:124: attempt to perform arithmetic on global 'log_in_time' (a nil value)

Auto PUP & deploy
If no target selected when pet dies /ja Deploy <t> spams chat log until something is targeted
Suggest <bt> if possible

Basic.lua

Line 10: Update to bring in line with Main File Examples files (add SMDinclude/) 
Line 174: Remove last comma

Suggestion
Basic info.txt
Line 1: change gearswap/common/ to gearswap/libs/

**Comment by smd111** [comment]
pup.lua fixed
Basic.lua fixed
(i still need to push them)

does it work from libs/?? i have never tried it

**Comment by Kilgannon2113** [comment]
yes.

common doesn't exist natively.. and creating the dir and placing the files there did not work for me.

/libs/SMDinclude works just fine

**Comment by smd111** [comment]
thanks its now fixed

**Comment by smd111** [comment]
i would like to let you know that gearswap does support what i said by default from the first download
`gearswap_data .. 'common/',` (line 704 of refresh.lua)
